@HotelListing.Api_HostAddress = https://localhost:7095
@json = application/json

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: {{json}}
{
  "Name" : "Babylon",
  "Address" : "Baghdad",
  "Rating" : 5,
  "CountryId" : 2
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/2

###
GET {{HotelListing.Api_HostAddress}}/api/hotels/3

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/7
Content-Type: {{json}}

{
  "Id" : 7,
  "Name" : "Test5445",
  "Address" : "Baghdad",
  "Rating" : 5,
  "CountryId" : 4
}

###

GET {{HotelListing.Api_HostAddress}}/api/countries
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NWYxYzg1Mi1kYjk0LTQyYWEtOGU2Zi1mYjIwYmM3Yjk0OGIiLCJlbWFpbCI6ImFkbWluNTU1NTU1NUBnbWFpbC5jb20iLCJqdGkiOiI4ZWQwZGZiYS02MjYzLTQ1NmMtODEyMy1hY2RmNTRkNzlmYjQiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU4NjE3NTkxLCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.CLN9Zl-JZlFRB_p-vXNVyIEsYQRI3xzXMXeih-sqcQk


###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: {{json}}
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NWYxYzg1Mi1kYjk0LTQyYWEtOGU2Zi1mYjIwYmM3Yjk0OGIiLCJlbWFpbCI6ImFkbWluNTU1NTU1NUBnbWFpbC5jb20iLCJqdGkiOiI4NGIxZGNmOS03OTZkLTQyYjAtYTE0Zi1mMmYxYThlNWViYmEiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzU4NjEzNzQ3LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.Ad0HkQo0fKejpElN0TceAfkYz5DR1B2Ay8PvHvf1B6A

{
    "Name": "Saudi Arabi",
    "ShortName": "SAD"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/2

###
GET {{HotelListing.Api_HostAddress}}/api/countries/4

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/3
Content-Type: {{json}}

{
    "Id" : 3,
    "Name": "Okrain",
    "ShortName": "OKR"
}

###
POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}
{
  "email" : "abdala@gmail.com",
  "password" : "P@ssowrd1"
}

###
POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}
{
  "email" : "abdala@gmail.com",
  "password" : "P@ssowrd1"
}
###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email" : "admin5555555@gmail.com",
  "password" : "P@ssowrd1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email" : "admin5555555@gmail.com",
  "password" : "P@ssowrd1",
  "firstName" : "First",
  "lastName" : "Last",
  "role" : "Administrator"
}
###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterUserDto
}

###
