@HotelListing.Api_HostAddress = https://localhost:7095

GET {{HotelListing.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

@id=0
GET {{HotelListing.Api_HostAddress}}/api/hotels/2

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/2

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Id" : 5,
    "name": "Hotel 4",
    "address": "Address 1",
    "rating": 4.5
}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/0
Content-Type: application/json

{
    "name": "Hotel 3",
    "address": "Address 1",
    "rating": 5
}

###
